### PR TITLE
UPD:Changes Enigma Timestamp

### PR DESCRIPTION
**Pull request by PragyaPR06**
Screenshot 2024-01-19 153119

1) Added year button for filtering the data
2)Adjusted the cards styling as per instructions
3)Keep the about section in accordance with Abacus page

NOTE: Need to adjust the About section in the mobile view.Working on it

### CODE REVIEW

**Comment by PragyaPR06** [comment]
Screenshot 2024-01-19 153029

**Comment by PragyaPR06** [comment]
Screenshot 2024-01-19 153042

**Comment by PragyaPR06** [comment]
Screenshot 2024-01-19 153029
Screenshot 2024-01-19 153014
Screenshot 2024-01-19 152955

**Review by dev-AshishRanjan — APPROVED** [review]

**Pull request merged**
